services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: ura-heat
    restart: unless-stopped
    tty: true
    working_dir: /var/www

    volumes:
      - ./app:/var/www
      - ./docker-files/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker-files/php/php.ini-development:/usr/local/etc/php/php.ini

    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 5s

    ports:
      - "8100:80"
      - "8143:443"

    volumes:
      - ./app:/var/www
      - ./docker-files/nginx/conf.d/:/etc/nginx/conf.d/

    networks:
      - app-network

  db:
    image: mariadb:latest
    container_name: db
    restart: unless-stopped
    tty: true

    ports:
      - "3306:3306"

    environment:
      #MARIADB_USER: dbuser
      #MARIADB_PASSWORD: 12345
      #MARIADB_DATABASE: laravel
      #MARIADB_ROOT_PASSWORD: 123456

      #MYSQL_DATABASE: laravel
      #MYSQL_ROOT_PASSWORD: 12345

      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: db_laravel
      MYSQL_USER: db_user
      MYSQL_PASSWORD: 12345

    volumes:
      - ./dbdata:/var/lib/mysql
      - ./docker-files/mysql/my.cnf:/etc/mysql/my.cnf

    networks:
      - app-network

volumes:
  dbdata:
    driver: local

networks:
  app-network:
    driver: bridge
